In [5]:
import sys
sys.path.append(r'../../')
from get_data import Data

input_dim=(0,)
train_num=52
data=Data("../.././data/data.txt",input_dim,train_num)

#训练指数模型

from scipy.optimize import curve_fit
import matplotlib.pyplot as plt
import numpy as np

def func(x, a, b,c):
    return a*x**b + c


#归一化

#xdata=data.train.mean_and_std_X[:,0]
#ydata=data.train.mean_and_std_Y[:,0]
xdata=data.train.X[:,0]
ydata=data.train.Y[:,0]


popt, pcov = curve_fit(func, xdata, ydata,maxfev=500000)
#popt数组中，三个值分别是待求参数a,b,c
#y2 = [func(i, popt[0],popt[1],popt[2]) for i in xdata]
print("模型参数")
print(popt)

pre_y=[]
for x in data.test.X:
    pre_y.append(func(x,popt[0],popt[1],popt[2]))
pre_y=np.array(pre_y)

err_sum=0.0
print("\n真实值\t预测值\t\t误差率")
for a,b in zip(data.test.Y , pre_y):
    err_sum+=abs(a-b)/a
    print(a,b,abs(a-b)/a)
print("平均误差率:",err_sum/data.test.Y.shape[0])

    

模型参数
[  1.79520603e+04   5.50927396e-04  -1.79476980e+04]

真实值	预测值		误差率
[ 20.8] [ 19.63243482] [ 0.05613294]
[ 20.1] [ 20.04667136] [ 0.00265317]
[ 16.9] [ 17.87840786] [ 0.05789396]
[ 16.3] [ 17.33344941] [ 0.0634018]
[ 16.4] [ 19.55812807] [ 0.19256879]
[ 19.] [ 18.78268609] [ 0.01143757]
[ 16.] [ 15.89920391] [ 0.00629976]
[ 20.] [ 17.70649142] [ 0.11467543]
[ 15.5] [ 16.24463238] [ 0.0480408]
[ 16.5] [ 15.90074556] [ 0.03631845]
[ 19.] [ 18.57071581] [ 0.0225939]
[ 17.] [ 18.82637684] [ 0.10743393]
[ 17.6] [ 19.22659221] [ 0.09242001]
[ 20.1] [ 18.59070845] [ 0.07508913]
[ 17.9] [ 18.02378159] [ 0.00691517]
[ 17.] [ 17.68720406] [ 0.04042377]
[ 17.] [ 15.98975321] [ 0.05942628]
[ 18.7] [ 17.74879185] [ 0.05086675]
[ 19.2] [ 21.20180926] [ 0.1042609]
平均误差率: [ 0.06046592]


In [6]:
import sys
sys.path.append(r'../../')
from get_data import Data

input_dim=(1,)
train_num=52
data=Data("../.././data/data.txt",input_dim,train_num)

#训练指数模型

from scipy.optimize import curve_fit
import matplotlib.pyplot as plt
import numpy as np

def func(x, a, b,c):
    return a*x**b + c


#归一化

#xdata=data.train.mean_and_std_X[:,0]
#ydata=data.train.mean_and_std_Y[:,0]
xdata=data.train.X[:,0]
ydata=data.train.Y[:,0]


popt, pcov = curve_fit(func, xdata, ydata,maxfev=500000)
#popt数组中，三个值分别是待求参数a,b,c
#y2 = [func(i, popt[0],popt[1],popt[2]) for i in xdata]
print("模型参数")
print(popt)

pre_y=[]
for x in data.test.X:
    pre_y.append(func(x,popt[0],popt[1],popt[2]))
pre_y=np.array(pre_y)

err_sum=0.0
print("\n真实值\t预测值\t\t误差率")
for a,b in zip(data.test.Y , pre_y):
    err_sum+=abs(a-b)/a
    print(a,b,abs(a-b)/a)
print("平均误差率:",err_sum/data.test.Y.shape[0])

    

模型参数
[ 5.8471138   0.354177    4.32189643]

真实值	预测值		误差率
[ 20.8] [ 19.89069777] [ 0.04371645]
[ 20.1] [ 20.85607041] [ 0.03761544]
[ 16.9] [ 18.37415827] [ 0.0872283]
[ 16.3] [ 16.79918893] [ 0.03062509]
[ 16.4] [ 18.10146425] [ 0.10374782]
[ 19.] [ 19.17720656] [ 0.00932666]
[ 16.] [ 15.64596485] [ 0.0221272]
[ 20.] [ 18.32586973] [ 0.08370651]
[ 15.5] [ 16.34160664] [ 0.0542972]
[ 16.5] [ 15.99765639] [ 0.03044507]
[ 19.] [ 18.03304617] [ 0.05089231]
[ 17.] [ 17.60926491] [ 0.03583911]
[ 17.6] [ 18.78584543] [ 0.06737758]
[ 20.1] [ 18.87940916] [ 0.06072591]
[ 17.9] [ 18.80369556] [ 0.05048579]
[ 17.] [ 18.40173558] [ 0.08245503]
[ 17.] [ 16.53683697] [ 0.02724488]
[ 18.7] [ 18.06144751] [ 0.03414719]
[ 19.2] [ 20.98705399] [ 0.09307573]
平均误差率: [ 0.05289891]


In [7]:
import sys
sys.path.append(r'../../')
from get_data import Data

input_dim=(2,)
train_num=52
data=Data("../.././data/data.txt",input_dim,train_num)

#训练指数模型

from scipy.optimize import curve_fit
import matplotlib.pyplot as plt
import numpy as np

def func(x, a, b,c):
    return a*x**b + c


#归一化

#xdata=data.train.mean_and_std_X[:,0]
#ydata=data.train.mean_and_std_Y[:,0]
xdata=data.train.X[:,0]
ydata=data.train.Y[:,0]


popt, pcov = curve_fit(func, xdata, ydata,maxfev=500000)
#popt数组中，三个值分别是待求参数a,b,c
#y2 = [func(i, popt[0],popt[1],popt[2]) for i in xdata]
print("模型参数")
print(popt)

pre_y=[]
for x in data.test.X:
    pre_y.append(func(x,popt[0],popt[1],popt[2]))
pre_y=np.array(pre_y)

err_sum=0.0
print("\n真实值\t预测值\t\t误差率")
for a,b in zip(data.test.Y , pre_y):
    err_sum+=abs(a-b)/a
    print(a,b,abs(a-b)/a)
print("平均误差率:",err_sum/data.test.Y.shape[0])

    

模型参数
[ 5.67448883  0.4746912   2.38332013]

真实值	预测值		误差率
[ 20.8] [ 20.01866564] [ 0.03756415]
[ 20.1] [ 18.48596688] [ 0.08030016]
[ 16.9] [ 18.57065135] [ 0.09885511]
[ 16.3] [ 17.42845902] [ 0.06923061]
[ 16.4] [ 17.70042154] [ 0.079294]
[ 19.] [ 18.98691982] [ 0.00068843]
[ 16.] [ 17.70042154] [ 0.10627635]
[ 20.] [ 19.86431576] [ 0.00678421]
[ 15.5] [ 17.87879986] [ 0.15347096]
[ 16.5] [ 18.40078666] [ 0.11519919]
[ 19.] [ 18.57065135] [ 0.0225973]
[ 17.] [ 18.57065135] [ 0.09239126]
[ 17.6] [ 19.31179931] [ 0.09726132]
[ 20.1] [ 21.62688798] [ 0.07596458]
[ 17.9] [ 18.48596688] [ 0.03273558]
[ 17.] [ 18.57065135] [ 0.09239126]
[ 17.] [ 18.90459418] [ 0.11203495]
[ 18.7] [ 20.47299138] [ 0.09481237]
[ 19.2] [ 19.78657238] [ 0.03055065]
平均误差率: [ 0.07360013]
